name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Generate iOS xcodeproj
      run: swift package generate-xcodeproj
    - name: Run iOS tests
      run: xcodebuild build test -destination 'name=iPhone 11' -scheme 'Swift Drawing Tools-Package'
